version: "3.2"
services:
  db:
    image: postgres:9.6.8
    restart: always
    environment:
      POSTGRES_USER: gengine
      POSTGRES_PASSWORD: gengine
      POSTGRES_DB: gengine

  adminer:
    image: adminer:4.6.2
    restart: always
    ports:
      - 8081:8080

  memcached:
      image: memcached:1.5.7

  actidoo:
#     build: actidoo
     image: imartinezortiz/actidoo-gamification-engine-docker
     depends_on:
       - db
       - memcached
     command: ["/usr/local/bin/wait-for-it.sh", "db:5432", "--", "/usr/local/bin/docker-entrypoint.sh"]
     ports:
       - 8080:6543
